apiVersion: v1
kind: ConfigMap
metadata:
  name: wk18-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This web page is housed on a Pod running Nginx </h1>
    </html>
